// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _u64_dlog{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const u64 * k1, const u64 * k2);
  const size_t sizes[2];

  u64 * key;
  datalog_item_data * value;
  icy_mem * key_area;
  icy_mem * value_area;
}u64_dlog;

u64_dlog * u64_dlog_create(const char * optional_name);
void u64_dlog_set(u64_dlog * table, u64 key, datalog_item_data value);
void u64_dlog_insert(u64_dlog * table, u64 * key, datalog_item_data * value, size_t count);
void u64_dlog_lookup(u64_dlog * table, u64 * keys, size_t * out_indexes, size_t count);
void u64_dlog_remove(u64_dlog * table, u64 * keys, size_t key_count);
void u64_dlog_clear(u64_dlog * table);
void u64_dlog_unset(u64_dlog * table, u64 key);
bool u64_dlog_try_get(u64_dlog * table, u64 * key, datalog_item_data * value);
void u64_dlog_print(u64_dlog * table);
size_t u64_dlog_iter(u64_dlog * table, u64 * keys, size_t keycnt, u64 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
