// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _u64_lookup{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const u64 * k1, const u64 * k2);
  const size_t sizes[1];

  u64 * key;
  icy_mem * key_area;
}u64_lookup;

u64_lookup * u64_lookup_create(const char * optional_name);
void u64_lookup_set(u64_lookup * table, u64 key);
void u64_lookup_insert(u64_lookup * table, u64 * key, size_t count);
void u64_lookup_lookup(u64_lookup * table, u64 * keys, size_t * out_indexes, size_t count);
void u64_lookup_remove(u64_lookup * table, u64 * keys, size_t key_count);
void u64_lookup_clear(u64_lookup * table);
void u64_lookup_unset(u64_lookup * table, u64 key);
bool u64_lookup_try_get(u64_lookup * table, u64 * key);
void u64_lookup_print(u64_lookup * table);
size_t u64_lookup_iter(u64_lookup * table, u64 * keys, size_t keycnt, u64 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
