// This file is auto generated by icy-table.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif


u64_lookup * u64_lookup_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"key"};
  static const char * const column_types[] = {"u64"};
  u64_lookup * instance = calloc(sizeof(u64_lookup), 1);
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  icy_table_init((icy_table * )instance, optional_name, 1, (unsigned int[]){sizeof(u64)}, (char *[]){(char *)"key"});
  
  return instance;
}

void u64_lookup_insert(u64_lookup * table, u64 * key, size_t count){
  void * array[] = {(void* )key};
  icy_table_inserts((icy_table *) table, array, count);
}

void u64_lookup_set(u64_lookup * table, u64 key){
  void * array[] = {(void* )&key};
  icy_table_inserts((icy_table *) table, array, 1);
}

void u64_lookup_lookup(u64_lookup * table, u64 * keys, size_t * out_indexes, size_t count){
  icy_table_finds((icy_table *) table, keys, out_indexes, count);
}

void u64_lookup_remove(u64_lookup * table, u64 * keys, size_t key_count){
  size_t indexes[key_count];
  size_t index = 0;
  size_t cnt = 0;
  while(0 < (cnt = icy_table_iter((icy_table *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    icy_table_remove_indexes((icy_table *) table, indexes, cnt);
    index = 0;
  }
}

void u64_lookup_clear(u64_lookup * table){
  icy_table_clear((icy_table *) table);
}

void u64_lookup_unset(u64_lookup * table, u64 key){
  u64_lookup_remove(table, &key, 1);
}

bool u64_lookup_try_get(u64_lookup * table, u64 * key){
  void * array[] = {(void* )key};
  void * column_pointers[] = {(void *)table->key};
  size_t __index = 0;
  icy_table_finds((icy_table *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  unsigned int sizes[] = {sizeof(u64)};
  for(int i = 1; i < 1; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void u64_lookup_print(u64_lookup * table){
  icy_table_print((icy_table *) table);
}

size_t u64_lookup_iter(u64_lookup * table, u64 * keys, size_t keycnt, u64 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator){
  return icy_table_iter((icy_table *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
